name: "Froling Data Collector"
description: "Collects data from Froling Systems"
version: "0.2.0"
slug: "froling_data_collector"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
map:
  - share:rw
